import { ThemeDefinition } from './types.js';

export const themeD: ThemeDefinition = {
  id: 'theme-d',
  code: 'Theme D',
  name: 'Enchanted Forest',
  subtitle: 'Druidic Sanctuary of the Ancient Tree',
  badge: 'DRUID-GROVE',
  icon: 'Sparkles',
  requiredLevel: 4,
  unlockTitle: 'Grove Wanderer',
  colors: {
    bg: '#02150d',
    surface: '#062b1d',
    surfaceHover: '#0a3d2b',
    border: 'rgba(52, 211, 153, 0.25)',
    primary: '#10b981',
    primaryHover: '#34d399',
    secondary: '#059669',
    accent: '#34d399',
    gold: '#fbbf24',
    text: '#ecfdf5',
    muted: '#6ee7b7',
    cardGlow: 'rgba(52, 211, 153, 0.3)',
    gradientBg: 'radial-gradient(ellipse at top, #063d28 0%, #02150d 75%)',
  },
  typography: {
    headingFont: '"Cinzel", "Georgia", serif',
    bodyFont: '"Inter", system-ui, sans-serif',
    monoFont: '"Courier New", monospace',
  },
  effects: {
    borderRadius: '0.85rem',
    cardBorderWidth: '1.5px',
    glassmorphic: true,
    scanlines: false,
    boxShadow: '0 8px 30px rgba(2, 21, 13, 0.8), 0 0 20px -3px rgba(52, 211, 153, 0.25)',
  },
  terminology: {
    quest: 'Grove Rite',
    quests: 'Sacred Bounties',
    boss: 'Corrupted Blight Treant',
    character: 'Archdruid Ranger',
    skills: 'World Tree Branches',
    xp: 'Anima Essence',
    currency: 'Spirit Dew',
    realmProgress: 'Spirit Tree Bloom',
    realmMetric: 'Purity Level',
  },
  hero: {
    name: 'Sylva Whisperwind',
    class: 'Verdant Archdruid',
    avatarEffect: 'floating-spores',
    weapon: 'Runed Elder Staff',
    gearSlots: ['Crown of Antlers', 'Cloak of Living Bramble', 'Staff of Yggdrasil', 'Emerald Talisman'],
  },
  boss: {
    name: 'Malakor, The Blight Treant',
    title: 'Corruptor of the Ancient Sapling',
    maxHp: 1200,
    avatarType: 'treant',
    flavor: 'Thorns and blackened sap threaten to choke the life of the holy grove. Defeat it through vitality and fitness!',
  },
  worldProgress: {
    title: 'Ancient World Tree Restoration',
    description: 'Each quest completed purifies corrupted roots and makes the luminescent canopy bloom with spirit flowers.',
  },
  preview: {
    bannerGradient: 'from-emerald-950 via-green-950 to-teal-950',
    cardGradient: 'from-emerald-600/10 via-teal-500/5 to-transparent',
    tag: 'Theme D',
    features: ['Bioluminescent floating spores', 'Elder staff druid rig', 'World Tree blooming milestones'],
  },
};
