import { ThemeDefinition } from './types.js';

export const themeE: ThemeDefinition = {
  id: 'theme-e',
  code: 'Theme E',
  name: 'Last Samurai Standing',
  subtitle: 'Path of Bushido & The Blood Moon',
  badge: 'BUSHIDO-HONOR',
  icon: 'Sword',
  requiredLevel: 5,
  unlockTitle: 'Bushido Blade',
  colors: {
    bg: '#09090b',
    surface: '#121216',
    surfaceHover: '#1c1b22',
    border: 'rgba(220, 38, 38, 0.3)',
    primary: '#dc2626',
    primaryHover: '#ef4444',
    secondary: '#991b1b',
    accent: '#f87171',
    gold: '#f59e0b',
    text: '#fafaf9',
    muted: '#a8a29e',
    cardGlow: 'rgba(220, 38, 38, 0.25)',
    gradientBg: 'radial-gradient(ellipse at top, #240a0c 0%, #09090b 75%)',
  },
  typography: {
    headingFont: '"Noto Serif JP", serif',
    bodyFont: '"Inter", system-ui, sans-serif',
    monoFont: '"Courier New", monospace',
  },
  effects: {
    borderRadius: '0.4rem',
    cardBorderWidth: '1.5px',
    glassmorphic: true,
    scanlines: false,
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.8), 0 0 20px -3px rgba(220, 38, 38, 0.25)',
  },
  terminology: {
    quest: 'Bushido Duty',
    quests: 'Honor Decrees',
    boss: 'Shadow Shogun Kurokage',
    character: 'Wandering Ronin',
    skills: 'Katana Stances & Kata',
    xp: 'Honor Points',
    currency: 'Koban Gold',
    realmProgress: 'Dojo & Torii Restoration',
    realmMetric: 'Honor Rank',
  },
  hero: {
    name: 'Jin Sakai',
    class: 'Master Ronin',
    avatarEffect: 'sakura-petals',
    weapon: 'Twin Muramasa Blades',
    gearSlots: ['Menpo War Mask', 'Crimson Lacquer Armor', 'Twin Katana Daisho', 'Ancestral Seal'],
  },
  boss: {
    name: 'Kurokage, The Shadow Shogun',
    title: 'Lord of the Burning Torii',
    maxHp: 1500,
    avatarType: 'shogun',
    flavor: 'A fallen warlord seeking to extinguish the last ember of samurai discipline. Strike down his shadow with creative mastery!',
  },
  worldProgress: {
    title: 'Sacred Mountain Shrine & Dojo',
    description: 'Restore ancestral stone lanterns, raise red torii gates, and cleanse the sacred dojo with completed duties.',
  },
  preview: {
    bannerGradient: 'from-red-950 via-zinc-950 to-neutral-950',
    cardGradient: 'from-red-600/10 via-amber-500/5 to-transparent',
    tag: 'Theme E',
    features: ['Falling sakura cherry petals', 'Katana slash battle animations', 'Ancestral torii gate restoration'],
  },
};
