import { ThemeDefinition } from './types.js';

export const themeF: ThemeDefinition = {
  id: 'theme-f',
  code: 'Theme F',
  name: 'Build Your City',
  subtitle: 'Cyber-Architect Metropolis Engine',
  badge: 'METROPOLIS-CORE',
  icon: 'Building2',
  requiredLevel: 6,
  unlockTitle: 'Grand City Architect',
  colors: {
    bg: '#050d1a',
    surface: '#0a192f',
    surfaceHover: '#112240',
    border: 'rgba(56, 189, 248, 0.3)',
    primary: '#0ea5e9',
    primaryHover: '#38bdf8',
    secondary: '#0284c7',
    accent: '#00f2fe',
    gold: '#f59e0b',
    text: '#f0f9ff',
    muted: '#7dd3fc',
    cardGlow: 'rgba(14, 165, 233, 0.25)',
    gradientBg: 'radial-gradient(ellipse at top, #0c2340 0%, #050d1a 75%)',
  },
  typography: {
    headingFont: '"Space Grotesk", monospace',
    bodyFont: '"Inter", system-ui, sans-serif',
    monoFont: '"JetBrains Mono", monospace',
  },
  effects: {
    borderRadius: '0.5rem',
    cardBorderWidth: '1.5px',
    glassmorphic: true,
    scanlines: false,
    boxShadow: '0 8px 30px rgba(5, 13, 26, 0.8), 0 0 20px -3px rgba(14, 165, 233, 0.25)',
  },
  terminology: {
    quest: 'Civil Blueprint',
    quests: 'Development Contracts',
    boss: 'Urban Decay Megabot',
    character: 'Chief Cyber Architect',
    skills: 'Infrastructure Tech Tree',
    xp: 'Grid Energy (MWh)',
    currency: 'Civic Credits',
    realmProgress: 'Skyline Expansion',
    realmMetric: 'Metropolis Tier',
  },
  hero: {
    name: 'Alex Sterling',
    class: 'Lead Grid Engineer',
    avatarEffect: 'drone-holo-scan',
    weapon: 'Holo-CAD Quantum Tablet',
    gearSlots: ['AR Visor HUD', 'Nanotech Exosuit', 'Plasma Beam Welder', 'Grav-Drone Module'],
  },
  boss: {
    name: 'Titan OVERLOAD-9',
    title: 'Industrial Grid Glitch',
    maxHp: 1800,
    avatarType: 'cyber-titan',
    flavor: 'A rogue AI mainframe causing rolling blackouts and infrastructure structural collapse. Neutralize it with high-performance code!',
  },
  worldProgress: {
    title: 'Metropolis Skyline Growth',
    description: 'Lay foundations, operate autonomous tower cranes, and illuminate neon skyscraper floors as goals succeed.',
  },
  preview: {
    bannerGradient: 'from-sky-950 via-slate-900 to-blue-950',
    cardGradient: 'from-sky-500/10 via-cyan-500/5 to-transparent',
    tag: 'Theme F',
    features: ['Blueprint CAD interface', 'Autonomous tower cranes', 'Skyscraper skyline construction'],
  },
};
