import { ThemeDefinition } from './types.js';

export const themeH: ThemeDefinition = {
  id: 'theme-h',
  code: 'Theme H',
  name: 'The Upside Down: Hawkins 1984',
  subtitle: 'Retro Analog Synthwave & Drifting Spores',
  badge: 'HAWKINS-1984',
  icon: 'Radio',
  requiredLevel: 8,
  unlockTitle: 'Dimensional Rift Walker',
  colors: {
    bg: '#050711',
    surface: '#0a0d1d',
    surfaceHover: '#131833',
    border: 'rgba(255, 15, 63, 0.35)',
    primary: '#ff0f3f',
    primaryHover: '#ff4d6d',
    secondary: '#06b6d4',
    accent: '#f59e0b',
    gold: '#fbbf24',
    text: '#f8fafc',
    muted: '#94a3b8',
    cardGlow: 'rgba(255, 15, 63, 0.3)',
    gradientBg: 'radial-gradient(ellipse at top, #2b0b17 0%, #050711 80%)',
  },
  typography: {
    headingFont: '"Press Start 2P", monospace',
    bodyFont: '"Merriweather", Georgia, serif',
    monoFont: '"Courier New", monospace',
  },
  effects: {
    borderRadius: '0.25rem',
    cardBorderWidth: '2px',
    glassmorphic: true,
    scanlines: true,
    boxShadow: '0 8px 32px rgba(5, 7, 17, 0.9), 0 0 25px -4px rgba(255, 15, 63, 0.35)',
  },
  terminology: {
    quest: 'Rift Incursion',
    quests: 'Hellfire Campaigns',
    boss: 'The Mind Flayer',
    character: 'Psionic Shadow Walker',
    skills: 'Telekinetic Synapse Matrix',
    xp: 'Rift Frequency (MHz)',
    currency: 'Arcade Tokens',
    realmProgress: 'Gate Containment',
    realmMetric: 'Rifts Closed',
  },
  hero: {
    name: 'Jane "Eleven" Hopper',
    class: 'Psionic Shadow Walker',
    avatarEffect: 'mind-pulse',
    weapon: 'Telekinetic Focus Band',
    gearSlots: ['Walkie-Talkie Rig', 'Retro Denim Jacket', 'Eggo Waffle Amulet', 'Hellfire Club Dice'],
  },
  boss: {
    name: 'The Mind Flayer',
    title: 'Shadow Sovereign of the Upside Down',
    maxHp: 2500,
    avatarType: 'shadow-entity',
    flavor: 'A colossal psionic titan looming across dimensions over Hawkins 1984. Sever its hivemind connection through intense focus sprints!',
  },
  worldProgress: {
    title: 'Close the Hawkins Gate',
    description: 'Every quest executed seals tears in the dimensional fabric, saving the town from the spreading shadow hivemind.',
  },
  preview: {
    bannerGradient: 'from-red-950 via-slate-950 to-cyan-950',
    cardGradient: 'from-red-900/40 to-slate-950',
    tag: 'RETRO 80s SCI-FI',
    features: ['Floating Upside-Down Spores', 'Analog Synthwave BGM Drone', 'CRT Scanline Overlays', 'Hawkins Lab Lore'],
  },
};
