import { ThemeDefinition } from './types.js';

export const themeG: ThemeDefinition = {
  id: 'theme-g',
  code: 'Theme G',
  name: 'Haunted World: Cursed Necropolis',
  subtitle: 'Gothic Victorian Crypt & Spectral Fog',
  badge: 'CURSED-NECROPOLIS',
  icon: 'Ghost',
  requiredLevel: 7,
  unlockTitle: 'Master of the Crypt',
  colors: {
    bg: '#07090e',
    surface: '#0d131a',
    surfaceHover: '#141c26',
    border: 'rgba(16, 185, 129, 0.3)',
    primary: '#10b981',
    primaryHover: '#34d399',
    secondary: '#8b5cf6',
    accent: '#a855f7',
    gold: '#fbbf24',
    text: '#f1f5f9',
    muted: '#94a3b8',
    cardGlow: 'rgba(16, 185, 129, 0.25)',
    gradientBg: 'radial-gradient(ellipse at top, #16241f 0%, #07090e 75%)',
  },
  typography: {
    headingFont: '"Cinzel", Georgia, serif',
    bodyFont: '"Inter", system-ui, sans-serif',
    monoFont: '"Courier New", monospace',
  },
  effects: {
    borderRadius: '0.375rem',
    cardBorderWidth: '1.5px',
    glassmorphic: true,
    scanlines: false,
    boxShadow: '0 8px 32px rgba(4, 7, 10, 0.9), 0 0 25px -4px rgba(16, 185, 129, 0.3)',
  },
  terminology: {
    quest: 'Crypt Rite',
    quests: 'Grave Trials',
    boss: 'Lord Malathrax, The Cursed Lich',
    character: 'Eldritch Sorcerer',
    skills: 'Forbidden Grimoire',
    xp: 'Soul Essence',
    currency: 'Grave Obols',
    realmProgress: 'Phylactery Seal Purity',
    realmMetric: 'Banished Specters',
  },
  hero: {
    name: 'Moros Nightshade',
    class: 'Eldritch Sorcerer',
    avatarEffect: 'spectral-souls',
    weapon: 'Soulforged Bone Staff',
    gearSlots: ['Obsidian Sigil Hood', 'Spectral Shroud', 'Amulet of the Grave', 'Gargoyle Familiar'],
  },
  boss: {
    name: 'Lord Malathrax, The Cursed Lich',
    title: 'Monarch of the Spectral Necropolis',
    maxHp: 2100,
    avatarType: 'undead-lich',
    flavor: 'An ancient dread sorcerer wielding soul-binding procrastination curses. Shatter his phylactery with unwavering study and discipline!',
  },
  worldProgress: {
    title: 'Banish the Ancient Curse',
    description: 'Each completed trial weakens the necrotic veil and restores hallowed purity to the fallen catacombs.',
  },
  preview: {
    bannerGradient: 'from-emerald-950 via-slate-900 to-purple-950',
    cardGradient: 'from-emerald-900/40 to-slate-950',
    tag: 'GOTHIC HORROR',
    features: ['Ethereal Graveyard Mist', 'Gothic Pipe Organ Soundscape', 'Spectral Spellcasting', 'Phylactery Boss Fights'],
  },
};
